// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/bencohen/Documents/Coding/clerk-webhook/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/bencohen/Documents/Coding/clerk-webhook/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
